// Renders one self-contained HTML document from a `DashboardData` domain object -- inline CSS
// (light/dark via `prefers-color-scheme`), no chart library and no CDN (zero-dep policy: CSS
// bars instead of a canvas/SVG chart library), every wide table wrapped for horizontal
// scrolling instead of overflowing the page. Pure and deterministic: this function reads
// nothing but its `data` argument and never calls `Date.now()` itself -- the one place "now"
// matters (the freshness banner's viewer-clock comparison) is deferred to a small inline
// `<script>` that runs in the READER's browser at view time, not at generation time, so the
// generated bytes themselves stay byte-identical for a fixed `data` (see
// test/unit/dashboard-render.test.ts's determinism case).

import type {
  AttributionPanel,
  CalibrationPanel,
  CohortPanel,
  CostPanel,
  DashboardData,
  DashboardEmptyReasonConfig,
  EmptyPanelReason,
  EmptyPanelReasonCode,
  FreshnessPanel,
  PanelMeta,
} from "./types.js";

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function fmtNum(n: number | null): string {
  return n === null ? "欠測" : String(n);
}

function fmtUsd(n: number | null): string {
  return n === null ? "欠測" : `$${n.toFixed(4)}`;
}

function fmtPercent(n: number | null): string {
  return n === null ? "欠測" : `${(n * 100).toFixed(1)}%`;
}

function fmtRatio(n: number | null): string {
  return n === null ? "欠測" : n.toFixed(2);
}

/** Clamps a ratio (e.g. 0.0-1.0-and-beyond) to a 0-100 CSS bar width -- a ratio can legitimately
 * exceed 1.0 (e.g. actual tokens over-shooting a prediction), but the bar itself never renders
 * past 100% of its track; the raw number is always printed alongside the bar too. */
function barWidthPercent(ratio: number | null, capAt = 1): string {
  if (ratio === null) return "0%";
  const clamped = Math.max(0, Math.min(ratio / capAt, 1));
  return `${(clamped * 100).toFixed(1)}%`;
}

function renderMetaLine(m: PanelMeta): string {
  return `<p class="panel-meta">N=${m.n} / 欠測率=${fmtPercent(m.missingRate)} / quality=${escapeHtml(m.qualityStatus)}</p>`;
}

/** Fixed, non-operator-editable sentence per reason code -- this framing is what guarantees
 * `withheld` can never be misread as "not measured" (spec requirement), so it stays literal here
 * rather than becoming free text a config file could accidentally weaken. Only the elaboration
 * alongside it (`EmptyPanelReason.note`) is operator-supplied. */
const EMPTY_REASON_SENTENCE: Record<EmptyPanelReasonCode, string> = {
  not_produced:
    "データなし（未生成: この種類のデータを生成する工程がまだ一度も実行されていません）",
  withheld:
    "データなし（非公開: 測定はしていますが、公開範囲の判断により意図的に非公開にしています）",
  insufficient_data: "データなし（データ不足: 件数が判定に必要な閾値に達していません）",
};

/** Renders the notice for a genuinely empty panel (n=0 or zero rows). With no `reason` supplied
 * -- the default, and the only path before this classification existed -- renders the original
 * plain "データなし", byte-identical to the prior behavior (dashboard-render.test.ts pins this).
 * With a `reason`, replaces it with the code's fixed, honest sentence plus the operator's own
 * `note`, never the reverse (a reason is never inferred here from data alone). */
function renderEmptyNotice(reason?: EmptyPanelReason): string {
  if (!reason) return `<p class="empty-notice">データなし</p>`;
  const sentence = EMPTY_REASON_SENTENCE[reason.code];
  const note = reason.note ? ` ${escapeHtml(reason.note)}` : "";
  return `<p class="empty-notice empty-notice-${reason.code}">${sentence}${note}</p>`;
}

/** Renders a `CostGroup`'s cost cell: the exact total when the group is complete, an
 * "incomplete" badge plus the known lower bound when some priced record is missing its cost
 * figure, or "欠測" when nothing priced was ever recorded at all. Never the partial sum
 * unlabeled -- see CostGroup's own doc comment for why. */
function renderCostCell(g: {
  totalCostUsd: number | null;
  knownCostLowerBoundUsd: number | null;
}): string {
  if (g.totalCostUsd !== null) return fmtUsd(g.totalCostUsd);
  if (g.knownCostLowerBoundUsd !== null) {
    return `<span class="badge-incomplete">不完全</span> 少なくとも ${fmtUsd(g.knownCostLowerBoundUsd)}`;
  }
  return "欠測";
}

function renderCostPanel(panel: CostPanel): string {
  const rows =
    panel.groups.length === 0
      ? renderEmptyNotice()
      : `<div class="table-wrap"><table>
      <thead><tr><th>repo</th><th>month</th><th>records</th><th>priced</th><th>unpriced</th><th>unknown</th><th>priced-missing-cost</th><th>total cost (priced only)</th></tr></thead>
      <tbody>
        ${panel.groups
          .map(
            (g) => `<tr>
          <td>${escapeHtml(g.repo)}</td>
          <td>${escapeHtml(g.month)}</td>
          <td>${g.recordCount}</td>
          <td>${g.pricedCount}</td>
          <td>${g.unpricedCount}</td>
          <td>${g.unknownCount}</td>
          <td>${g.pricedMissingCostCount}</td>
          <td>${renderCostCell(g)}</td>
        </tr>`,
          )
          .join("\n")}
      </tbody>
    </table></div>`;

  return `<section id="panel-cost">
    <h2>1. Cost</h2>
    ${renderMetaLine(panel.meta)}
    <p class="panel-note">unpriced/unknown な record は total cost に含めていない (「$0」に潰していない)。priced が 0 件の repo x month は total cost を「欠測」表示、priced の一部で cost が欠測している repo x month は total cost を「不完全」バッジ付きの下限値表示にする -- 部分合計を完全な合計として見せない。</p>
    ${rows}
  </section>`;
}

function renderCalibrationPanel(panel: CalibrationPanel, reason?: EmptyPanelReason): string {
  const summaryLine =
    panel.sampleStatus === "insufficient_data"
      ? `<p class="panel-note">sample 不足 (predicted N=${panel.predictedRows.length}) -- 区間・平均は insufficient_data として非表示。個々の行は下表参照。</p>`
      : `<p class="panel-note">平均 ratio (actual tokens / predicted p50): ${fmtRatio(panel.averageRatioToP50)}</p>`;

  const predictedTable =
    panel.predictedRows.length === 0
      ? renderEmptyNotice(reason)
      : `<div class="table-wrap"><table>
      <thead><tr><th>generated_at</th><th>cohort</th><th>predicted p50</th><th>predicted p80</th><th>actual tokens</th><th>actual cost</th><th>ratio (actual/p50)</th></tr></thead>
      <tbody>
        ${panel.predictedRows
          .map(
            (r) => `<tr>
          <td>${escapeHtml(r.generatedAt)}</td>
          <td>${escapeHtml(r.cohortDigest)}</td>
          <td>${fmtNum(r.predictedP50)}</td>
          <td>${fmtNum(r.predictedP80)}</td>
          <td>${r.actualTokens}</td>
          <td>${fmtUsd(r.actualCostUsd)}</td>
          <td>
            <div class="bar-track"><div class="bar-fill" style="width:${barWidthPercent(r.ratioToP50, 2)}"></div></div>
            ${fmtRatio(r.ratioToP50)}
          </td>
        </tr>`,
          )
          .join("\n")}
      </tbody>
    </table></div>`;

  const abstainReasonRows = Object.entries(panel.abstainReasonCounts).sort(([a], [b]) =>
    a.localeCompare(b),
  );
  const abstainTable =
    abstainReasonRows.length === 0
      ? `<p class="empty-notice">abstain なし</p>`
      : `<div class="table-wrap"><table>
      <thead><tr><th>abstain reason</th><th>count</th></tr></thead>
      <tbody>
        ${abstainReasonRows
          .map(([reason, count]) => `<tr><td>${escapeHtml(reason)}</td><td>${count}</td></tr>`)
          .join("\n")}
      </tbody>
    </table></div>`;

  return `<section id="panel-calibration">
    <h2>2. Forecast calibration</h2>
    ${renderMetaLine(panel.meta)}
    <p class="panel-note">欠測率は「p50 または p80 のいずれかが欠測」の行比率。p50 欠測=${panel.missingP50Count}行 / p80 欠測=${panel.missingP80Count}行 (それぞれ独立にカウント -- 片方だけ欠測の行もある)。</p>
    <p class="panel-note">区間 (信頼区間等) は計算しない -- sample 不足時は insufficient_data と正直に表示する (M1 DoD)。</p>
    ${summaryLine}
    <h3>Predicted (n=${panel.predictedRows.length})</h3>
    ${predictedTable}
    <h3>Abstained (n=${panel.abstainedCount})</h3>
    ${abstainTable}
  </section>`;
}

function renderAttributionPanel(panel: AttributionPanel, reason?: EmptyPanelReason): string {
  const table =
    panel.timeSeries.length === 0
      ? renderEmptyNotice(reason)
      : `<div class="table-wrap"><table>
      <thead><tr><th>generated_at</th><th>source repo</th><th>exactly attributed</th><th>unbound</th><th>mixed</th><th>orphan</th><th>exact token ratio</th></tr></thead>
      <tbody>
        ${panel.timeSeries
          .map(
            (p) => `<tr>
          <td>${escapeHtml(p.generatedAt)}</td>
          <td>${escapeHtml(p.sourceRepo)}</td>
          <td>${p.exactlyAttributed}</td>
          <td>${p.unbound}</td>
          <td>${p.mixed}</td>
          <td>${p.orphan}</td>
          <td>
            <div class="bar-track"><div class="bar-fill" style="width:${barWidthPercent(p.exactAttributedTokenRatio)}"></div></div>
            ${fmtPercent(p.exactAttributedTokenRatio)}
          </td>
        </tr>`,
          )
          .join("\n")}
      </tbody>
    </table></div>`;

  const eligibility =
    panel.latestResearchEligible === null ? "欠測" : panel.latestResearchEligible ? "yes" : "no";

  return `<section id="panel-attribution">
    <h2>3. Attribution</h2>
    ${renderMetaLine(panel.meta)}
    <p class="panel-note">research_eligible (直近): ${escapeHtml(eligibility)}</p>
    ${table}
  </section>`;
}

function hoursAgoLabel(iso: string | null): string {
  if (iso === null) return "欠測";
  return escapeHtml(iso);
}

function renderFreshnessPanel(panel: FreshnessPanel): string {
  return `<section id="panel-freshness">
    <h2>4. Freshness</h2>
    ${renderMetaLine(panel.meta)}
    <div
      id="freshness-banner"
      class="freshness-banner freshness-unknown"
      data-generated-at="${escapeHtml(panel.generatedAt)}"
      data-pipeline-heartbeat-at="${panel.pipelineHeartbeatAt ? escapeHtml(panel.pipelineHeartbeatAt) : ""}"
      data-last-valid-event-at="${panel.lastValidEventAt ? escapeHtml(panel.lastValidEventAt) : ""}"
    >
      <p class="freshness-text">(JavaScript 無効時はここに表示されません -- 下の生の値を参照してください)</p>
    </div>
    <ul class="freshness-raw">
      <li>pipeline_heartbeat_at (直近の workflow 実行): ${hoursAgoLabel(panel.pipelineHeartbeatAt)}</li>
      <li>last_valid_event_at (直近の有効データ): ${hoursAgoLabel(panel.lastValidEventAt)}</li>
      <li>このダッシュボードの生成時刻: ${escapeHtml(panel.generatedAt)}</li>
    </ul>
  </section>`;
}

function renderCohortPanel(panel: CohortPanel, reason?: EmptyPanelReason): string {
  const table =
    panel.groups.length === 0
      ? renderEmptyNotice(reason)
      : `<div class="table-wrap"><table>
      <thead><tr><th>cohort_digest</th><th>records</th><th>total actual cost</th></tr></thead>
      <tbody>
        ${panel.groups
          .map(
            (g) => `<tr>
          <td>${escapeHtml(g.cohortDigest)}</td>
          <td>${g.recordCount}</td>
          <td>${fmtUsd(g.totalActualCostUsd)}</td>
        </tr>`,
          )
          .join("\n")}
      </tbody>
    </table></div>`;

  return `<section id="panel-cohort">
    <h2>5. Model cohort</h2>
    ${renderMetaLine(panel.meta)}
    <p class="panel-caveat">${escapeHtml(panel.caveat)}</p>
    ${table}
  </section>`;
}

const STYLE = `
:root {
  --bg: #ffffff;
  --fg: #1a1a1a;
  --muted: #5a5a5a;
  --border: #d8d8d8;
  --surface: #f6f6f6;
  --bar: #4a7dbf;
  --ok: #2f7a3a;
  --warn: #8a6d1a;
  --danger: #9b2c2c;
  --warn-bg: #fdf3d8;
  --danger-bg: #fbe2e2;
}
@media (prefers-color-scheme: dark) {
  :root {
    --bg: #14161a;
    --fg: #e8e8e8;
    --muted: #a0a0a0;
    --border: #3a3d42;
    --surface: #1e2126;
    --bar: #6fa3e0;
    --ok: #6fd188;
    --warn: #e0c168;
    --danger: #e88a8a;
    --warn-bg: #3a3320;
    --danger-bg: #3a2222;
  }
}
* { box-sizing: border-box; }
body {
  background: var(--bg);
  color: var(--fg);
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
  margin: 0;
  padding: 1.5rem;
  line-height: 1.5;
}
h1 { font-size: 1.4rem; }
h2 { font-size: 1.15rem; border-bottom: 1px solid var(--border); padding-bottom: 0.3rem; margin-top: 2rem; }
h3 { font-size: 1rem; color: var(--muted); }
section { margin-bottom: 2rem; }
.panel-meta { color: var(--muted); font-size: 0.85rem; }
.panel-note, .panel-caveat { color: var(--muted); font-size: 0.85rem; }
.empty-notice { color: var(--muted); font-style: italic; }
.table-wrap { overflow-x: auto; max-width: 100%; }
table { border-collapse: collapse; width: 100%; font-size: 0.85rem; }
th, td { border: 1px solid var(--border); padding: 0.35rem 0.5rem; text-align: left; white-space: nowrap; }
th { background: var(--surface); }
.bar-track { display: inline-block; width: 80px; height: 8px; background: var(--surface); border: 1px solid var(--border); vertical-align: middle; margin-right: 0.4rem; }
.bar-fill { height: 100%; background: var(--bar); }
.badge-incomplete { display: inline-block; border: 1px solid var(--warn); color: var(--warn); border-radius: 3px; padding: 0 0.3rem; font-size: 0.75rem; margin-right: 0.3rem; }
.freshness-banner { border: 1px solid var(--border); border-radius: 4px; padding: 0.6rem 0.8rem; margin: 0.5rem 0; }
.freshness-ok { border-color: var(--ok); color: var(--ok); }
.freshness-yellow { border-color: var(--warn); background: var(--warn-bg); color: var(--warn); }
.freshness-red { border-color: var(--danger); background: var(--danger-bg); color: var(--danger); }
.freshness-raw { color: var(--muted); font-size: 0.8rem; }
footer { color: var(--muted); font-size: 0.75rem; margin-top: 2rem; }
`;

/** One small, inline, no-dependency comparison of the VIEWER's current clock against the three
 * timestamps embedded on #freshness-banner's data-* attributes -- deliberately not computed at
 * generation time (spec: "生成時刻と閲覧時刻を JS 1行で比較"), and deliberately reporting the
 * heartbeat and last-valid-event axes as two independent findings so a reader can tell "the
 * runner stopped executing" apart from "the runner is fine, there's just nothing new." */
const FRESHNESS_SCRIPT = `
(function () {
  var el = document.getElementById("freshness-banner");
  if (!el) return;
  var nowMs = Date.now();
  function hoursSince(iso) {
    if (!iso) return null;
    var t = Date.parse(iso);
    return Number.isNaN(t) ? null : (nowMs - t) / 3600000;
  }
  var hb = hoursSince(el.getAttribute("data-pipeline-heartbeat-at"));
  var ev = hoursSince(el.getAttribute("data-last-valid-event-at"));
  var messages = [];
  var level = "ok";
  if (hb === null) { messages.push("pipeline heartbeat が記録されていません (pipeline が動いていない可能性)"); level = "red"; }
  else if (hb >= 48) { messages.push("pipeline heartbeat が48時間以上更新されていません (pipeline 停止の可能性)"); level = "red"; }
  else if (hb >= 24) { messages.push("pipeline heartbeat が24時間以上更新されていません"); level = "yellow"; }
  if (ev === null) { messages.push("有効なデータイベントが記録されていません"); if (level !== "red") level = "yellow"; }
  else if (ev >= 48) { messages.push("新しいタスクデータが48時間以上ありません (pipeline は動いているが新規データが無い可能性)"); if (level !== "red") level = "yellow"; }
  else if (ev >= 24) { messages.push("新しいタスクデータが24時間以上ありません"); if (level === "ok") level = "yellow"; }
  if (messages.length === 0) messages.push("直近24時間以内に pipeline heartbeat / データの両方を確認済みです");
  el.className = "freshness-banner freshness-" + level;
  var textEl = el.querySelector(".freshness-text");
  if (textEl) textEl.textContent = messages.join(" / ");
})();
`;

/** `emptyReasons` is entirely optional and, when omitted, changes nothing: every panel renders
 * exactly as it did before this classification existed (dashboard-render.test.ts's "no config"
 * case pins this). Cost and Freshness never take a reason -- neither ever calls
 * `renderEmptyNotice`, so their output is untouched by this parameter regardless. */
export function renderDashboardHtml(
  data: DashboardData,
  emptyReasons?: DashboardEmptyReasonConfig,
): string {
  return `<!doctype html>
<html lang="ja">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>agent-metrics dashboard</title>
<style>${STYLE}</style>
</head>
<body>
<h1>agent-metrics dashboard</h1>
<p class="panel-meta">生成時刻: ${escapeHtml(data.generatedAt)}</p>
<p class="panel-note">因果を主張しない: このダッシュボードはコスト・件数・速度の記述的な観測のみを示す。品質は測定していない (quality_status: not_measured)。</p>
${renderCostPanel(data.cost)}
${renderCalibrationPanel(data.calibration, emptyReasons?.calibration)}
${renderAttributionPanel(data.attribution, emptyReasons?.attribution)}
${renderFreshnessPanel(data.freshness)}
${renderCohortPanel(data.cohort, emptyReasons?.cohort)}
<footer>agent-metrics-harvester dashboard generator</footer>
<script>${FRESHNESS_SCRIPT}</script>
</body>
</html>
`;
}
